### ISSUE TITLE
ReferenceError: Keycloak is not defined

### ISSUE THREAD

**Issue by QuantumSolver** [matejbucek/Secure_Svelte_With_Keycloak#2]
Hi, followed your tutorial. on both old and updated beanch i get this error.. 
i even tried copying your source code. same error everytime

**Comment by MarioPiccolella** [comment]
Yes, i got the same error, can't understand how to fix it.

**Comment by QuantumSolver** [comment]
working on a work around.. 
gonna use rest instead 

https://documenter.getpostman.com/view/7294517/SzmfZHnd#91d9f10d-2216-4a82-a2fe-cd446155416a

**Comment by matejbucek** [comment]
It seems to me that your code executes before the keycloak library is loaded. 
I am currently trying to solve this by packaging keycloak-js right into the bundle so it is loaded before your code executes.

**Comment by matejbucek** [comment]
I have just pushed new commit that should solve the issue. 
It solved it at least for me. I no longer get Keycloak is not defined error.

The problem was that Svelte SSR tried to init Keycloak whilst prerendering. 
Keycloak should be initialised in browser (CSR).

**Comment by ogaims** [comment]
The issue still persists with SvelteKit. It works quite unreliable.
